// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sandu_Ana_Alexandra_Proiect.Data;

namespace Sandu_Ana_Alexandra_Proiect.Migrations
{
    [DbContext(typeof(Sandu_Ana_Alexandra_ProiectContext))]
    [Migration("20201220204336_Trei")]
    partial class Trei
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sandu_Ana_Alexandra_Proiect.Models.Ghid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Dataangajare")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeGhid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ghid");
                });

            modelBuilder.Entity("Sandu_Ana_Alexandra_Proiect.Models.Vacanta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dataplecare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datasosire")
                        .HasColumnType("datetime2");

                    b.Property<int>("GhidID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Tara")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GhidID");

                    b.ToTable("Vacanta");
                });

            modelBuilder.Entity("Sandu_Ana_Alexandra_Proiect.Models.Vacanta", b =>
                {
                    b.HasOne("Sandu_Ana_Alexandra_Proiect.Models.Ghid", "Ghid")
                        .WithMany("Vacante")
                        .HasForeignKey("GhidID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
